### ISSUE TITLE
[Spring Boot 3.3.1] -  java.lang.NoClassDefFoundError: io/opentelemetry/api/incubator/metrics/DoubleGauge 

### ISSUE THREAD

**Issue by tiarebalbi** [grafana/grafana-opentelemetry-starter#62]
* **Spring Boot:** `3.3.1`
* **Dependency:** `com.grafana:grafana-opentelemetry-starter:1.4.0` 

The error below started to happen after upgrading from Spring Boot `3.2.6` to `3.3.1`.

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'autoConfiguredOpenTelemetrySdk' defined in class path resource [com/grafana/opentelemetry/OpenTelemetryConfig.class]: Failed to instantiate [io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdk]: Factory method 'autoConfiguredOpenTelemetrySdk' threw exception with message: io/opentelemetry/api/incubator/metrics/DoubleGauge
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:636) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1337) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1167) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory$2.resolveCandidate(DefaultListableBeanFactory.java:1927) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.createOptionalDependency(DefaultListableBeanFactory.java:1930) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:904) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:782) ~[spring-beans-6.1.10.jar:6.1.10]
	... 130 common frames omitted
```

Lower level exception:
```
Caused by: java.lang.NoClassDefFoundError: io/opentelemetry/api/incubator/metrics/DoubleGauge
	at io.opentelemetry.sdk.metrics.SdkMeter.gaugeBuilder(SdkMeter.java:111) ~[opentelemetry-sdk-metrics-1.37.0.jar:1.37.0]
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.<init>(BatchSpanProcessor.java:203) ~[opentelemetry-sdk-trace-1.37.0.jar:1.37.0]
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.<init>(BatchSpanProcessor.java:162) ~[opentelemetry-sdk-trace-1.37.0.jar:1.37.0]
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor.<init>(BatchSpanProcessor.java:87) ~[opentelemetry-sdk-trace-1.37.0.jar:1.37.0]
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessorBuilder.build(BatchSpanProcessorBuilder.java:159) ~[opentelemetry-sdk-trace-1.37.0.jar:1.37.0]
	at io.opentelemetry.sdk.autoconfigure.TracerProviderConfiguration.configureBatchSpanProcessor(TracerProviderConfiguration.java:126) ~[opentelemetry-sdk-extension-autoconfigure-1.37.0.jar:1.37.0]
	at io.opentelemetry.sdk.autoconfigure.TracerProviderConfiguration.configureSpanProcessors(TracerProviderConfiguration.java:92) ~[opentelemetry-sdk-extension-autoconfigure-1.37.0.jar:1.37.0]
	at io.opentelemetry.sdk.autoconfigure.TracerProviderConfiguration.configureTracerProvider(TracerProviderConfiguration.java:62) ~[opentelemetry-sdk-extension-autoconfigure-1.37.0.jar:1.37.0]
	at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.build(AutoConfiguredOpenTelemetrySdkBuilder.java:464) ~[opentelemetry-sdk-extension-autoconfigure-1.37.0.jar:1.37.0]
	at com.grafana.opentelemetry.OpenTelemetryConfig.autoConfiguredOpenTelemetrySdk(OpenTelemetryConfig.java:94) ~[grafana-opentelemetry-starter-1.4.0.jar:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:140) ~[spring-beans-6.1.10.jar:6.1.10]
	... 147 common frames omitted
Caused by: java.lang.ClassNotFoundException: io.opentelemetry.api.incubator.metrics.DoubleGauge
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[na:na]
	... 160 common frames omitted
```

**Comment by zeitlinger** [comment]
this repo is now archived - see https://github.com/grafana/grafana-opentelemetry-starter?tab=readme-ov-file#overview
